module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.4.2-unstable
cabal-file: project.cabal
hidden-packages: monads-tf
version: 1
extra-packages: mtl 2.1.2
ghc-args: []
excluded-modules: []
